// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UI49un45DCtl7JqBwyce1hkg_ePwbKs',
    appId: '1:55640900910:android:2a08f309a4e7f93a1d26bf',
    messagingSenderId: '55640900910',
    projectId: 'kuwrir-3495d',
    storageBucket: 'kuwrir-3495d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUMbbkr5ZYpulBhee1kAwbwAhW6H-cxE',
    appId: '1:55640900910:ios:f72d8472ae6316611d26bf',
    messagingSenderId: '55640900910',
    projectId: 'kuwrir-3495d',
    storageBucket: 'kuwrir-3495d.firebasestorage.app',
    androidClientId: '55640900910-5a3nl97tl5qfaknhaerf58ai5gvscnr6.apps.googleusercontent.com',
    iosClientId: '55640900910-ts11eopdqk1b1cpknifqr65abnf18bri.apps.googleusercontent.com',
    iosBundleId: 'com.kuwrir.merchant',
  );
}
